server:
  port: 8180
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: book-service
#logging:
#  level:
#    root: debug
http:
  logging:
    enabled: true
    log-body: false
    log-level: INFO
aspect:
  enabled: true
  on-timer: true
  log-level: WARN