server:
  port: 8280
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: issue-service
http:
  logging:
    enabled: true
    log-body: false
    log-level: WARN
aspect:
  enabled: true
  on-timer: true
  log-level: ERROR